### ISSUE TITLE
docker-compose does not work properly with ecr-login

### ISSUE THREAD

**Issue by nvanheuverzwijn** [pottava/dockerized-ecr-credential-helper#1]
I am submitting this as an issue because I am not sure how to integrate this little work around in the README.

I just stumble across a problem regarding docker-compose and ecr-login. As of docker-compose version 1.13.0, adding the script `/usr/bin/docker-credentials-ecr-login` will prevent docker-compose to fetch image from public repository. This error will occur :

```
docker.errors.DockerException: Credentials store error: StoreError('Credentials store docker-credential-ecr-login exited with "".',)
```

The problem seems to lies with docker-compose itself for either not supporting `credHelpers` or trying to authenticate on repository that do not need authentication. However, here is an alternate `docker-credentials-ecr-login` script which allows docker-compose to pull images from ecr and public registry:

```
#!/bin/sh
  SECRET=$(docker --config /dev/null run --rm \
    -e METHOD=$1 \
    -e REGISTRY=$(cat -) \
    -e AWS_ACCESS_KEY_ID \
    -e AWS_SECRET_ACCESS_KEY \
    pottava/amazon-ecr-credential-helper)
  RESPONSE=$(echo $SECRET | grep Secret);
  if [ -z $RESPONSE ]; then
    echo '{ "Username": "", "Secret": ""}'
  else
    echo $RESPONSE
  fi
```

We could even handle this inside the container but I think this workaround is good enough.

Thank you for your time and your work,
Cheers,
Nic

**Comment by HelLViS69** [comment]
I have the same problem.. pulling using docker pull works, but with docker-compose doesn't

**Comment by pottava** [comment]
Sorry for the inconvenience, everyone.
@nvanheuverzwijn Thanks for your advice. I've just updated the README.
